---
deployment:
  tasks:
    # --- VARIABEL PATH ---
    - export DEPLOYPATH=/home/lemg1635/koperasi/
    - export PUBLICPATH=/home/lemg1635/public_html/koperasi/

    # --- 1. SETUP FOLDER ---
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $PUBLICPATH

    # --- 2. UPDATE CORE APP ---
    # Copy logika aplikasi ke folder luar (Secure)
    # Exclude 'public' agar tidak salah kamar
    - /usr/bin/rsync -av --exclude='.git' --exclude='.cpanel.yml' --exclude='public' . $DEPLOYPATH

    # --- 3. UPDATE PUBLIC ASSETS ---
    # Copy isi folder 'public' ke dalam folder subdomain
    # Exclude 'storage' agar symlink gambar tidak tertimpa folder kosong
    - /usr/bin/rsync -av --exclude='storage' public/ $PUBLICPATH

    # --- 4. OPTIMASI & DATABASE ---
    - cd $DEPLOYPATH
    
    # Fix Permission Storage (Penting di cPanel)
    - /bin/chmod -R 775 storage bootstrap/cache

    # Maintenance Mode ON
    - /usr/local/bin/php artisan down || true

    # Migrate & Clear Cache
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan optimize:clear
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan route:cache

    # Maintenance Mode OFF
    - /usr/local/bin/php artisan up